### ISSUE TITLE
start_app()

### ISSUE THREAD

**Issue by mirecl** [Zalozhnyy/sber_test_api#3]
Где используется?:
https://github.com/Zalozhnyy/sber_test_api/blob/7d30e5144370cbdc08db58dfdb4c457bfcf3d9c7/start_app.py#L14

**Comment by Zalozhnyy** [comment]
Функция используется для старта приложения из docker-compose.yml

gunicorn start_app:start_app --bind 0.0.0.0:8080 --worker-class aiohttp.GunicornWebWorker --workers 12

**Comment by Zalozhnyy** [comment]
Добавлено использование в #11
